import {
  decodeSvgDataUri,
  isSvgImageSource,
  stripSvgPrologue,
} from "../client/editor/components/ViewerImage";
import { normalizeInlineSvg } from "../client/editor/components/InlinePanZoomViewer";

// Shaped like what hediet.vscode-drawio writes: an XML prologue, a DOCTYPE, a
// comment, and labels that only exist inside <foreignObject> — which is why an
// <img> shows the shapes but none of the text.
const DRAWIO_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Do not edit this file with editors other than draw.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="120px" height="60px" content="&lt;mxfile&gt;&lt;/mxfile&gt;">
<g><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">Label</div></foreignObject></g>
</svg>`;

const toDataUri = (svg: string) =>
  `data:image/svg+xml;base64,${Buffer.from(svg, "utf8").toString("base64")}`;

describe("isSvgImageSource", () => {
  it.each([
    "data:image/svg+xml;base64,AAA",
    "https://host/a.svg",
    "https://host/a.svg?v=2",
  ])("matches %s", (src) => {
    expect(isSvgImageSource(src)).toBe(true);
  });

  it.each(["", "https://host/a.png", "data:image/png;base64,AAA"])(
    "does not match %s",
    (src) => {
      expect(isSvgImageSource(src)).toBe(false);
    },
  );
});

describe("stripSvgPrologue", () => {
  it("drops the declaration, doctype and comments before the root element", () => {
    expect(stripSvgPrologue(DRAWIO_SVG).startsWith("<svg ")).toBe(true);
  });

  it("leaves markup that already starts at the root alone", () => {
    const svg = "<svg><rect/></svg>";
    expect(stripSvgPrologue(svg)).toBe(svg);
  });

  it("leaves markup with no root element alone", () => {
    expect(stripSvgPrologue("not svg at all")).toBe("not svg at all");
  });
});

describe("decodeSvgDataUri", () => {
  it("decodes a base64 payload and keeps the foreignObject labels", () => {
    const decoded = decodeSvgDataUri(toDataUri(DRAWIO_SVG));

    expect(decoded).toBeDefined();
    expect(decoded).toContain("<foreignObject");
    expect(decoded).toContain("Label");
    expect(decoded!.startsWith("<svg ")).toBe(true);
  });

  it("decodes a percent-encoded payload", () => {
    const svg = "<svg><text>ü</text></svg>";
    expect(
      decodeSvgDataUri(`data:image/svg+xml,${encodeURIComponent(svg)}`),
    ).toBe(svg);
  });

  it("strips scripts and inline event handlers", () => {
    const decoded = decodeSvgDataUri(
      toDataUri(
        `<svg onload="alert(1)"><script>alert(2)</script><rect/></svg>`,
      ),
    );

    expect(decoded).not.toContain("alert(1)");
    expect(decoded).not.toContain("alert(2)");
    expect(decoded).toContain("<rect/>");
  });

  it("returns nothing for a non-svg source", () => {
    expect(decodeSvgDataUri("https://host/a.svg")).toBeUndefined();
  });
});

describe("normalizeInlineSvg", () => {
  it("keeps the aspect ratio of a file with no viewBox", () => {
    const normalized = normalizeInlineSvg(stripSvgPrologue(DRAWIO_SVG));

    expect(normalized).toContain('viewBox="0 0 120 60"');
    expect(normalized).toContain('width="100%"');
    expect(normalized).toContain('height="100%"');
    expect(normalized).toContain('preserveAspectRatio="xMidYMid meet"');
  });

  it("keeps an existing viewBox", () => {
    const normalized = normalizeInlineSvg(
      '<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="-0.5 -0.5 120 60"><rect/></svg>',
    );

    expect(normalized).toContain('viewBox="-0.5 -0.5 120 60"');
  });

  it("leaves markup it cannot parse alone", () => {
    expect(normalizeInlineSvg("<svg><unclosed></svg>")).toBe(
      "<svg><unclosed></svg>",
    );
  });
});
