import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import {
  MAX_INLINE_SVG_BYTES,
  clearInlineSvgCache,
  isSvgPath,
  svgFileToDataUri,
} from "../host/inlineSvg";

const DRAWIO_SVG = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Do not edit this file with editors other than draw.io -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" width="120px" height="60px" viewBox="-0.5 -0.5 120 60">
  <g><foreignObject width="100%" height="100%"><div xmlns="http://www.w3.org/1999/xhtml">Schrütt</div></foreignObject></g>
</svg>`;

describe("isSvgPath", () => {
  it.each(["a.svg", "A.SVG", "/x/diagram.drawio.svg"])(
    "matches %s",
    (candidate) => {
      expect(isSvgPath(candidate)).toBe(true);
    },
  );

  it.each(["a.svgz", "a.png", "svg"])("does not match %s", (candidate) => {
    expect(isSvgPath(candidate)).toBe(false);
  });
});

describe("svgFileToDataUri", () => {
  let dir: string;

  beforeEach(() => {
    clearInlineSvgCache();
    dir = fs.mkdtempSync(path.join(os.tmpdir(), "inline-svg-"));
  });

  afterEach(() => {
    fs.rmSync(dir, { recursive: true, force: true });
  });

  const write = (name: string, content: string) => {
    const file = path.join(dir, name);
    fs.writeFileSync(file, content);
    return file;
  };

  it("encodes the file as a base64 svg data uri", () => {
    const uri = svgFileToDataUri(write("diagram.drawio.svg", DRAWIO_SVG));

    expect(uri).toBeDefined();
    expect(uri).toMatch(/^data:image\/svg\+xml;base64,/);
    expect(
      Buffer.from(uri!.split(",")[1], "base64").toString("utf8"),
    ).toBe(DRAWIO_SVG);
  });

  it("serves an unchanged file from the cache", () => {
    const file = write("a.svg", DRAWIO_SVG);
    const first = svgFileToDataUri(file);

    const readFileSync = jest.spyOn(fs, "readFileSync");
    expect(svgFileToDataUri(file)).toBe(first);
    expect(readFileSync).not.toHaveBeenCalled();
    readFileSync.mockRestore();
  });

  it("picks up a file rewritten on disk", () => {
    const file = write("a.svg", DRAWIO_SVG);
    const first = svgFileToDataUri(file);

    const later = new Date(Date.now() + 2000);
    fs.writeFileSync(file, `${DRAWIO_SVG}<!-- edited -->`);
    fs.utimesSync(file, later, later);

    expect(svgFileToDataUri(file)).not.toBe(first);
  });

  it("leaves a file too large to inline to the webview", () => {
    const file = path.join(dir, "huge.svg");
    fs.writeFileSync(file, Buffer.alloc(MAX_INLINE_SVG_BYTES + 1, 0x20));

    expect(svgFileToDataUri(file)).toBeUndefined();
  });

  it("returns nothing for a missing file", () => {
    expect(svgFileToDataUri(path.join(dir, "nope.svg"))).toBeUndefined();
  });

  it("returns nothing for a directory", () => {
    expect(svgFileToDataUri(dir)).toBeUndefined();
  });
});
